### ISSUE TITLE
Publish 16 reports on censorship events around the world

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-web#1302]
# Reports

- [x] Report 1: [Russia](https://ooni.org/post/2023-russia-a-year-after-the-conflict/)
- [x] Report 2: [Azerbaijan](https://ooni.org/post/2023-azerbaijan-internet-censorship/)
- [x] Report 3: [Kazakhstan](https://ooni.org/post/2023-throttling-kz-elections/)
- [x] Report 4: [Brazil](https://ooni.org/post/2023-brazil-telegram/)
- [x] Report 5: [China](https://ooni.org/post/2023-china-blocks-ooni/)
- [x] Report 6: [Senegal](https://ooni.org/post/2023-senegal-social-media-blocks/)
- [x] Report 7: [Jordan](https://ooni.org/post/2023-jordan-blocks-grindr/)
- [x] Report 8: [Tanzania](https://ooni.org/post/2024-tanzania-lgbtiq-censorship-and-other-targeted-blocks/)
- [x] Report 9: [Kazakhstan](https://ooni.org/post/2024-kazakhstan-report/)
- [x] Report 10: [Russia](https://ooni.org/post/2024-russia-blocked-ooni-explorer/)
- [x] Report 11: [Russia](https://ooni.org/post/2024-russia-report/)
- [x] Report 12: [Bangladesh](https://ooni.org/post/2025-bangladesh-report/)
- [x] Report 13: [Kenya](https://ooni.org/post/2025-kenya-blocked-telegram-kcse-exams/)
- [x] Report 14: [Tanzania](https://ooni.org/post/2025-tanzania-blocked-twitter/)
- [x] Report 15: [India-Pakistan](https://ooni.org/post/2025-media-censorship-in-india-and-pakistan/)
- [x] Report 16: [Turkey](https://ooni.org/post/2025-turkiye-throttling-social-media/)
- [x] Report 17: [Iran](https://ooni.org/post/2025-iran-censorship-womens-rights/)

# Description of activity

Since 2016, we have published [66 reports](https://ooni.org/reports/) on internet censorship around the world. We recently published an in-depth research report on new censorship events (based on OONI data) that emerged in Russia following the invasion of Ukraine. Many of these reports have been published in collaboration with local partners, who help contextualize and share the findings with their local communities. We have also published research in collaboration with international organizations (such as Amnesty International, OutRight Action International, and the University of Toronto’s Citizen Lab), as well as with other measurement projects (such as the Internet Outage Detection and Analysis (IODA) project, Censored Planet, and the Measurement Lab). 

As these reports present and contextualize OONI data findings, they have supported a wide range of research and advocacy efforts over the years. Freedom House has cited OONI research reports in many of their annual Freedom on the Net country reports. Journalists around the world (for example, from Deutsche Welle, Mada Masr, CNET, Time) have cited OONI research reports when reporting on emergent censorship events. Human rights advocates (particularly those from the global #KeepItOn campaign) regularly refer to our reports to inform their advocacy efforts. A few years ago, our report on the blocking of websites amid protests in Pakistan supported the petition of local organizations who challenged the legality of these blocks at the Islamabad High Court. 

We therefore aim to produce more research reports on censorship events as part of this proposed project. Unlike the Censorship Incident Reporting Platform (which will provide short reports with summary information, primarily aimed at supporting the rapid response efforts of journalists and activists), these research reports will **offer more in-depth analysis of censorship events** so that they can better support research, advocacy, journalism, and legal efforts both in the short-term and in the long-term. We will seek relevant collaboration with our partners in order to share expertise and disseminate the findings more widely. 

In particular, we aim to collaborate with local partners (with a focus on working with minority populations) on drafting, publishing, and disseminating research reports on censorship events. Our work on these reports will primarily involve OONI data analysis, the writing and interpretation of technical censorship measurement findings, as well as any other research and writing that is required for the reports. We will provide financial support to local partners for their role in such research efforts. 

We will encourage local partners to support this research by:

- Coordinating OONI Probe testing in their countries
- Updating the Citizen Lab test lists (i.e. lists of URLs measured for censorship)
- Contributing relevant contextual information to the reports (such as information about the country’s legal and political environment)
- Disseminating the censorship findings in their communities. 

If possible, we will also support partners to conduct interviews (the findings of which may support our reports), in an effort to investigate the impact of blocks on local communities.

**Comment by agrabeli** [comment]
We have exceed the goals of this activity, having published 17 research reports (instead of 16). This activity is complete and I am closing this ticket.
